# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://iqmuphdcmgfeunuronhx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbXVwaGRjbWdmZXVudXJvbmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4NTY1OTQsImV4cCI6MjAzMTQzMjU5NH0.k037OMqAOtH8_O7JdIr9p0qK66v_kMHdxjUJ4b3qDIU"